version: "3.8"

services:
  app:
    build: .
    container_name: user_service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456789
      - DB_NAME=user_service
    restart: unless-stopped
      
  db:
    image: mysql:8.0
    container_name: user_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "user_service"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql

volumes:
  mysql_data:
